/**
 * Each Choice position has a fixed colour and Pin so Players can name it out
 * loud: Lave (volcano), Lagon (dolphin), Soleil (sun), Forêt (palm tree).
 * Colours come from the quiz-scoped tokens in src/app/reunion/quiz.css; the
 * Pins are generated by `npm run reunion:photos` from drafts/reunion/pins/.
 */
const POSITIONS = [
  {
    pin: '/reunion/pins/lava.webp',
    className: 'bg-(--color-lave) text-white',
  },
  {
    pin: '/reunion/pins/lagoon.webp',
    className: 'bg-(--color-lagon) text-white',
  },
  {
    pin: '/reunion/pins/sun.webp',
    className: 'bg-(--color-soleil) text-navy',
  },
  {
    pin: '/reunion/pins/forest.webp',
    className: 'bg-(--color-foret) text-white',
  },
];

/** Side of the square Pin files, in px (`PIN_SIZE` in the script). */
const PIN_SIZE = 384;

/** The URL of every Pin, to save it for offline play. */
export const choicePinUrls = POSITIONS.map(({ pin }) => pin);

/** Background and text colour of a Choice position. */
export const choiceColours = (position: number) =>
  POSITIONS[position].className;

export const ChoicePin = ({
  position,
  className,
}: {
  position: number;
  className: string;
}) => (
  // biome-ignore lint/performance/noImgElement: the exact WebP URL must be cacheable offline, which the Next image optimiser's URLs are not.
  <img
    src={POSITIONS[position].pin}
    alt=""
    width={PIN_SIZE}
    height={PIN_SIZE}
    draggable={false}
    className={`shrink-0 object-contain ${className}`}
  />
);
